### ISSUE TITLE
Set up basic local & github repo

### ISSUE THREAD

**Issue by ArBridgeman** [ArBridgeman/java-test-api#3]
ACs
* [x] Use template from https://github.com/phoenix-games-holding/publishing-platform-team-backend-developer-trial-task 
* [x] Acquire relevant Java version via SDKman
  * Set up Java 17 LTS (with support for [jenv](https://www.jenv.be), if it's your thing)
* [x] Check that github tests are working
* [x] Set up IntelliJ with root, tests, etc. folders
* [x] Ensure existing tests work locally
  * All but 1 always succeed; this one has a slight time offset from what is expected
   ```bash
  # PreventStartupWarningHealthCheckTest.java > healthCheckCalled_returnsHealthy
   expected: Result{isHealthy=true, duration=0, timestamp=2023-04-30T16:31:46.203+02:00}
     but was: Result{isHealthy=true, duration=0, timestamp=2023-04-30T16:31:46.038+02:00}
   ```

**Comment by artvolk** [comment]
This 

> All but 1 always succeed; this one has a slight time offset from what is expected

was fixed here: 
https://github.com/phoenix-games-holding/publishing-platform-team-backend-developer-trial-task/commit/67c38a296a21496d3b0c10f8e9971c4ea4682f82
